export const GAMES_DATA = [
  // === 1-20: 叙事与哲学的巅峰 ===
  { id: 1, name_zh: "《极乐迪斯科》", name_en: "Disco Elysium - The Final Cut", steamAppId: 632470, genre: "CRPG/哲学", playtime: 25, desc: "“文学与游戏的完美结合。一场关于失败、政治、存在主义和宿醉的伟大辩论。”" },
  { id: 2, name_zh: "《星际拓荒》", name_en: "Outer Wilds", steamAppId: 753640, genre: "探索/神作", playtime: 20, desc: "“一生只能玩一次的奇迹。用好奇心驱动的宇宙探索，结局的浪漫与宏大无与伦比。”" },
  { id: 3, name_zh: "《尼尔：机械纪元》", name_en: "NieR: Automata", steamAppId: 524220, genre: "ARPG/剧情", playtime: 35, desc: "“横尾太郎的致郁美学。在废土上探讨‘人类’的定义，音乐是神级。”" },
  { id: 4, name_zh: "《荒野大镖客：救赎 2》", name_en: "Red Dead Redemption 2", steamAppId: 1174180, genre: "开放世界/史诗", playtime: 60, desc: "“开放世界的工业奇迹，更是亚瑟·摩根波澜壮阔又令人心碎的救赎史诗。”" },
  { id: 5, name_zh: "《巫师 3：狂猎》", name_en: "The Witcher 3: Wild Hunt", steamAppId: 292030, genre: "RPG/开放世界", playtime: 100, desc: "“波兰国宝。每一个支线都像一部短篇小说，塑造了最鲜活的奇幻世界。”" },
  { id: 6, name_zh: "《博德之门 3》", name_en: "Baldur's Gate 3", steamAppId: 1086940, genre: "CRPG/神作", playtime: 100, desc: "“CRPG 的新天花板。极高的自由度，真正由玩家书写的史诗。”" },
  { id: 7, name_zh: "《生化奇兵：无限》", name_en: "BioShock Infinite", steamAppId: 8870, genre: "FPS/剧情", playtime: 12, desc: "“天空之城的绝美与黑暗，多重宇宙的烧脑剧情，伊丽莎白是最好的伙伴。”" },
  { id: 8, name_zh: "《赛博朋克 2077》", name_en: "Cyberpunk 2077", steamAppId: 1091500, genre: "RPG/赛博朋克", playtime: 50, desc: "“夜之城没有活着的传奇。在 2.0 版本和《往日之影》后，它终于成为了真正的神作。”" },
  { id: 9, name_zh: "《质量效应：传奇版》", name_en: "Mass Effect Legendary Edition", steamAppId: 1328670, genre: "RPG/太空歌剧", playtime: 80, desc: "“太空歌剧的巅峰。横跨三部曲的选择与后果，薛帕德指挥官的传奇。”" },
  { id: 10, name_zh: "《最后生还者 第一部》", name_en: "The Last of Us Part I", steamAppId: 1888930, genre: "动作/叙事", playtime: 15, desc: "“叙事驱动动作游戏的教科书。乔尔与艾莉的末世公路之旅，探讨爱与自私。”" },
  { id: 11, name_zh: "《底特律：变人》", name_en: "Detroit: Become Human", steamAppId: 1222140, genre: "互动电影", playtime: 12, desc: "“互动电影的集大成者。仿生人是否拥有灵魂？你的选择决定三个种族的命运。”" },
  { id: 12, name_zh: "《SOMA》", name_en: "SOMA", steamAppId: 282140, genre: "恐怖/哲学", playtime: 10, desc: "“最被低估的科幻恐怖神作。关于意识上传、自我认知和深海的绝望哲学。”" },
  { id: 13, name_zh: "《艾迪芬奇的记忆》", name_en: "What Remains of Edith Finch", steamAppId: 501300, genre: "步行模拟/叙事", playtime: 3, desc: "“魔幻现实主义的短篇故事集。用十几种不同的玩法讲述一个家族的死亡与诅咒。”" },
  { id: 14, name_zh: "《去月球》", name_en: "To the Moon", steamAppId: 206440, genre: "像素/叙事", playtime: 4, desc: "“像素画风下的催泪核弹。一个关于记忆、遗憾和约定的简单故事。”" },
  { id: 15, name_zh: "《史丹利的寓言：超豪华版》", name_en: "The Stanley Parable: Ultra Deluxe", steamAppId: 1703340, genre: "Meta/幽默", playtime: 6, desc: "“对游戏叙事本身的解构与嘲弄。打破第四面墙的极致体验。”" },
  { id: 16, name_zh: "《哈迪斯》", name_en: "Hades", steamAppId: 1145360, genre: "肉鸽/动作", playtime: 30, desc: "“将叙事完美融入 Roguelike 死亡循环的典范。希腊神话的现代家庭伦理剧。”" },
  { id: 17, name_zh: "《传送门 2》", name_en: "Portal 2", steamAppId: 620, genre: "解谜/神作", playtime: 8, desc: "“解谜游戏的永恒神作。GLaDOS 的刻薄与 Wheatley 的愚蠢构成了完美的剧本。”" },
  { id: 18, name_zh: "《地狱之刃：塞娜的献祭》", name_en: "Hellblade: Senua's Sacrifice", steamAppId: 414340, genre: "动作/心理恐怖", playtime: 8, desc: "“戴上耳机，体验精神病患者耳边的低语。一场为了爱人灵魂的痛苦远征。”" },
  { id: 19, name_zh: "《这是我的战争》", name_en: "This War of Mine", steamAppId: 282070, genre: "生存/反战", playtime: 15, desc: "“在战争游戏中，你不再扮演士兵，而是手无寸铁的平民。对人性的终极拷问。”" },
  { id: 20, name_zh: "《奥伯拉丁的回归》", name_en: "Return of the Obra Dinn", steamAppId: 653530, genre: "推理/逻辑", playtime: 10, desc: "“推理游戏的逻辑巅峰。仅凭一块怀表和黑白画面，还原一艘幽灵船的真相。”" },

  // === 21-40: 玩法与机制的极致 ===
  { id: 21, name_zh: "《艾尔登法环》", name_en: "Elden Ring", steamAppId: 1245620, genre: "ARPG/开放世界", playtime: 80, desc: "“魂系游戏的集大成者。交界地的探索感前无古人，受苦与惊叹并存。”" },
  { id: 22, name_zh: "《只狼：影逝二度》", name_en: "Sekiro: Shadows Die Twice", steamAppId: 814380, genre: "动作/硬核", playtime: 30, desc: "“动作游戏的节奏巅峰。打铁的清脆声是最好的奖励，犹豫就会败北。”" },
  { id: 23, name_zh: "《黑暗之魂 3》", name_en: "Dark Souls III", steamAppId: 374320, genre: "ARPG/硬核", playtime: 40, desc: "“传火的终局。Boss 战设计极其精彩，末世凄凉美的极致。”" },
  { id: 24, name_zh: "《TUNIC》", name_en: "TUNIC", steamAppId: 553420, genre: "冒险/解谜", playtime: 15, desc: "“一款披着可爱狐狸外衣的硬核解谜神作，致敬老游戏说明书的设计天才。”" },
  { id: 25, name_zh: "《空洞骑士》", name_en: "Hollow Knight", steamAppId: 367520, genre: "银河恶魔城", playtime: 30, desc: "“银河恶魔城的现代标杆。圣巢的悲伤历史，精准的跳跃与战斗。”" },
  { id: 26, name_zh: "《杀戮尖塔》", name_en: "Slay the Spire", steamAppId: 646570, genre: "肉鸽/卡牌", playtime: 50, desc: "“卡牌肉鸽的开山鼻祖。数值平衡的艺术，让人欲罢不能的‘再来一把’。”" },
  { id: 27, name_zh: "《异星工厂》", name_en: "Factorio", steamAppId: 427520, genre: "模拟/自动化", playtime: 100, desc: "“自动化的极致浪漫。看着杂乱的传送带变成完美的流水线，强迫症的福音。”" },
  { id: 28, name_zh: "《环世界》", name_en: "RimWorld", steamAppId: 294100, genre: "模拟/故事生成", playtime: 100, desc: "“最强的故事生成器。从器官贩卖到星际逃亡，每个殖民地都有独特的血泪史。”" },
  { id: 29, name_zh: "《文明 6》", name_en: "Sid Meier's Civilization VI", steamAppId: 289070, genre: "策略/4X", playtime: 100, desc: "“‘再来一回合’的魔咒。见证人类文明从摇篮到星辰大海。”" },
  { id: 30, name_zh: "《幽浮 2》", name_en: "XCOM 2", steamAppId: 268500, genre: "策略/战棋", playtime: 40, desc: "“战棋游戏的策略巅峰。95%命中率Miss的绝望，培养士兵的羁绊。”" },
  { id: 31, name_zh: "《神界：原罪 2》", name_en: "Divinity: Original Sin 2", steamAppId: 435150, genre: "CRPG", playtime: 80, desc: "“元素交互的战棋玩法极其丰富，剧情自由度极高，CRPG 的入门首选。”" },
  { id: 32, name_zh: "《对马岛之魂：导演剪辑版》", name_en: "Ghost of Tsushima", steamAppId: 2215430, genre: "动作/开放世界", playtime: 40, desc: "“风会指引你。如电影般的武士复仇之旅，风景与战斗的完美结合。”" },
  { id: 33, name_zh: "《泰拉瑞亚》", name_en: "Terraria", steamAppId: 105600, genre: "沙盒/冒险", playtime: 80, desc: "“2D 沙盒的尽头。从挖泥土到击杀月球领主，内容量大到不可思议。”" },
  { id: 34, name_zh: "《星露谷物语》", name_en: "Stardew Valley", steamAppId: 413150, genre: "模拟/种田", playtime: 60, desc: "“逃离城市喧嚣的避风港。种田、钓鱼、恋爱，简单的生活最治愈。”" },
  { id: 35, name_zh: "《蔚蓝》", name_en: "Celeste", steamAppId: 504230, genre: "平台/跳跃", playtime: 15, desc: "“平台跳跃的满分答卷。将克服焦虑的心理路程完美融入高难度关卡中。”" },
  { id: 36, name_zh: "《死亡细胞》", name_en: "Dead Cells", steamAppId: 588650, genre: "肉鸽/动作", playtime: 30, desc: "“动作肉鸽的爽快感巅峰。丝滑的战斗手感，丰富的武器系统。”" },
  { id: 37, name_zh: "《半衰期：爱莉克斯》", name_en: "Half-Life: Alyx", steamAppId: 546560, genre: "VR/FPS", playtime: 15, desc: "“VR 游戏的工业革命。真正让人感觉穿越到了另一个维度的神作。”" },
  { id: 38, name_zh: "《毁灭战士：永恒》", name_en: "DOOM Eternal", steamAppId: 782330, genre: "FPS/爽游", playtime: 15, desc: "“FPS 的暴力美学。不是你在打恶魔，是恶魔被困在房间里和你打。”" },
  { id: 39, name_zh: "《泰坦陨落 2》", name_en: "Titanfall 2", steamAppId: 1237970, genre: "FPS/机甲", playtime: 8, desc: "“单人 FPS 战役的天花板之一。‘协议三：保护铁驭’，男人的浪漫是机甲。”" },
  { id: 40, name_zh: "《全面战争：战锤 3》", name_en: "Total War: WARHAMMER III", steamAppId: 1142710, genre: "策略/RTS", playtime: 100, desc: "“奇幻战争的终极模拟。超大地图，成百上千的兵种，宏大的史诗战场。”" },

  // === 41-60: 视听与艺术的盛宴 ===
  { id: 41, name_zh: "《Gris》", name_en: "GRIS", steamAppId: 683320, genre: "平台/艺术", playtime: 4, desc: "“每一帧都是壁纸。关于悲伤五阶段的水彩画卷，音乐极其空灵。”" },
  { id: 42, name_zh: "《风之旅人》", name_en: "Journey", steamAppId: 638230, genre: "冒险/治愈", playtime: 2, desc: "“禅意游戏的代表。无言的旅途，与陌生人的短暂相遇是最大的感动。”" },
  { id: 43, name_zh: "《奥日与萤火意志》", name_en: "Ori and the Will of the Wisps", steamAppId: 1057090, genre: "银河恶魔城", playtime: 15, desc: "“画面美到窒息，跑酷行云流水，剧情却像刀子一样扎心。”" },
  { id: 44, name_zh: "《茶杯头》", name_en: "Cuphead", steamAppId: 268910, genre: "动作/射击", playtime: 10, desc: "“30 年代橡皮管动画风格的复活。爵士乐与高难度 Boss 战的完美狂欢。”" },
  { id: 45, name_zh: "《控制》", name_en: "Control", steamAppId: 870780, genre: "动作/怪谈", playtime: 20, desc: "“新怪谈风格的视觉奇观。混凝土野兽派建筑与超自然力量的碰撞。”" },
  { id: 46, name_zh: "《生化危机 2 重制版》", name_en: "Resident Evil 2 Remake", steamAppId: 883710, genre: "恐怖/生存", playtime: 10, desc: "“经典重制的标杆。警察局的地图设计极其精妙，恐怖氛围恰到好处。”" },
  { id: 47, name_zh: "《死亡搁浅》", name_en: "Death Stranding Director's Cut", steamAppId: 1850570, genre: "动作/步行模拟", playtime: 50, desc: "“小岛秀夫的孤独美学。在支离破碎的世界中通过‘送快递’重新连接人心。”" },
  { id: 48, name_zh: "《赛博朋克酒保行动》", name_en: "VA-11 Hall-A", steamAppId: 447530, genre: "视觉小说/模拟", playtime: 10, desc: "“配着复古音乐调酒，听着赛博都市的琐碎故事，氛围感无敌。”" },
  { id: 49, name_zh: "《光之子》", name_en: "Child of Light", steamAppId: 256290, genre: "RPG/艺术", playtime: 10, desc: "“一首可玩的叙事长诗。水彩画风与回合制战斗的优雅结合。”" },
  { id: 50, name_zh: "《ABZÛ》", name_en: "ABZÛ", steamAppId: 384190, genre: "冒险/潜水", playtime: 2, desc: "“深海潜水模拟器。与鲸鱼共舞，体验海洋的静谧与壮丽。”" },
  { id: 51, name_zh: "《精灵与森林》", name_en: "Ori and the Blind Forest", steamAppId: 261570, genre: "银河恶魔城", playtime: 10, desc: "“梦幻般的开端，银之树的逃亡关卡配乐是游戏史上的经典。”" },
  { id: 52, name_zh: "《428：被封锁的涩谷》", name_en: "428: Shibuya Scramble", steamAppId: 648580, genre: "视觉小说/真人", playtime: 30, desc: "“真人视觉小说的巅峰，多线叙事产生的蝴蝶效应令人拍案叫绝。”" },
  { id: 53, name_zh: "《女神异闻录 5 皇家版》", name_en: "Persona 5 Royal", steamAppId: 1687950, genre: "JRPG", playtime: 100, desc: "“JRPG 的美术教科书。红黑撞色的 UI 设计，极具风格化的怪盗生活。”" },
  { id: 54, name_zh: "《八方旅人 2》", name_en: "Octopath Traveler II", steamAppId: 1971650, genre: "JRPG", playtime: 60, desc: "“HD-2D 风格的巅峰。光影效果绝美，八个旅人的故事交织。”" },
  { id: 55, name_zh: "《大神 绝景版》", name_en: "Okami HD", steamAppId: 587620, genre: "动作冒险", playtime: 35, desc: "“水墨风格的塞尔达。扮演天照大神，用画笔净化世界，真正的艺术品。”" },
  { id: 56, name_zh: "《最终幻想 7 重制版》", name_en: "Final Fantasy VII Remake Intergrade", steamAppId: 1462040, genre: "ARPG/JRPG", playtime: 40, desc: "“米德加的钢铁丛林从未如此真实。克劳德与蒂法、爱丽丝的重逢。”" },
  { id: 57, name_zh: "《巨像之子》", name_en: "Praey for the Gods", steamAppId: 494430, genre: "动作/生存", playtime: 15, desc: "“旺达与巨像的精神续作，在冰天雪地中攀爬巨兽，体验孤独的弑神之旅。”" },
  { id: 58, name_zh: "《多重花园》", name_en: "Manifold Garden", steamAppId: 473950, genre: "解谜/视觉", playtime: 6, desc: "“无限循环的几何世界。在埃舍尔风格的建筑中操纵重力，视觉奇观。”" },
  { id: 59, name_zh: "《画中世界》", name_en: "Gorogoa", steamAppId: 557600, genre: "解谜/艺术", playtime: 3, desc: "“全手绘的解谜艺术。通过移动画框来连接时空，创意令人惊叹。”" },
  { id: 60, name_zh: "《Hi-Fi RUSH》", name_en: "Hi-Fi RUSH", steamAppId: 1817230, genre: "动作/音游", playtime: 10, desc: "“色彩斑斓的节奏动作游戏。整个世界都在随音乐律动，快乐就是这么简单。”" },

  // === 61-80: 角色扮演与沉浸模拟 ===
  { id: 61, name_zh: "《上古卷轴 V：天际》", name_en: "The Elder Scrolls V: Skyrim", steamAppId: 489830, genre: "RPG/开放世界", playtime: 100, desc: "“开放世界的代名词。直到今天，我们依然想醒在那辆马车上。”" },
  { id: 62, name_zh: "《辐射：新维加斯》", name_en: "Fallout: New Vegas", steamAppId: 22380, genre: "RPG/废土", playtime: 50, desc: "“废土 RPG 的剧情巅峰。多方势力交错，选择真正影响世界走向。”" },
  { id: 63, name_zh: "《天国：拯救》", name_en: "Kingdom Come: Deliverance", steamAppId: 379430, genre: "RPG/中世纪", playtime: 60, desc: "“中世纪模拟器。从文盲铁匠之子成长为骑士，硬核且真实。”" },
  { id: 64, name_zh: "《杀出重围：人类革命》", name_en: "Deus Ex: Human Revolution", steamAppId: 238010, genre: "沉浸模拟/赛博", playtime: 25, desc: "“赛博朋克沉浸模拟的经典。关于身体改造与人性的哲学思考。”" },
  { id: 65, name_zh: "《耻辱 2》", name_en: "Dishonored 2", steamAppId: 403640, genre: "沉浸模拟/潜行", playtime: 20, desc: "“关卡设计的巅峰（如发条宅邸、时间这一关）。极高的玩法自由度。”" },
  { id: 66, name_zh: "《掠食》", name_en: "Prey", steamAppId: 480490, genre: "沉浸模拟/科幻", playtime: 20, desc: "“空间站箱庭设计的极致。任何物品都可能是外星人，极度烧脑。”" },
  { id: 67, name_zh: "《女神异闻录 4 黄金版》", name_en: "Persona 4 Golden", steamAppId: 1113000, genre: "JRPG", playtime: 70, desc: "“最完美的乡村青春悬疑剧。伙伴之间的羁绊描写是系列最佳。”" },
  { id: 68, name_zh: "《如龙 0》", name_en: "Yakuza 0", steamAppId: 638970, genre: "动作/剧情", playtime: 40, desc: "“日式极道的挽歌。桐生一马与真岛吾朗的传奇起点，热血与感动并存。”" },
  { id: 69, name_zh: "《最终幻想 X/X-2 HD》", name_en: "Final Fantasy X/X-2 HD Remaster", steamAppId: 359870, genre: "JRPG/经典", playtime: 60, desc: "“最凄美的爱情故事。优娜的异界送，水球比赛，还有那首《素敌だね》。”" },
  { id: 70, name_zh: "《勇者斗恶龙 XI S》", name_en: "Dragon Quest XI S", steamAppId: 1295510, genre: "JRPG/王道", playtime: 80, desc: "“王道 JRPG 的守护者。虽然故事老套，但它把‘勇者’二字演绎到了极致。”" },
  { id: 71, name_zh: "《传说之下》", name_en: "Undertale", steamAppId: 391540, genre: "RPG/Meta", playtime: 8, desc: "“颠覆 RPG 规则的神作。杀戮还是宽恕？你的每一个决定都会被记住。”" },
  { id: 72, name_zh: "《暗黑地牢》", name_en: "Darkest Dungeon", steamAppId: 262060, genre: "RPG/克苏鲁", playtime: 60, desc: "“克苏鲁风格的压力管理。看着英雄们崩溃发疯，体验绝望的深渊。”" },
  { id: 73, name_zh: "《Kenshi》", name_en: "Kenshi", steamAppId: 233860, genre: "沙盒/RPG", playtime: 100, desc: "“最自由的废土沙盒。你不是主角，你只是个随时会被强盗打死的路人。”" },
  { id: 74, name_zh: "《骑马与砍杀 2：霸主》", name_en: "Mount & Blade II: Bannerlord", steamAppId: 261550, genre: "RPG/策略", playtime: 100, desc: "“中世纪领主模拟器。带兵打仗、攻城略地，从中世纪雇佣兵到国王。”" },
  { id: 75, name_zh: "《恐怖黎明》", name_en: "Grim Dawn", steamAppId: 219990, genre: "ARPG/刷宝", playtime: 60, desc: "“暗黑类游戏的集大成者。双职业系统极其耐玩，刷装备的快乐。”" },
  { id: 76, name_zh: "《开拓者：正义之怒》", name_en: "Pathfinder: Wrath of the Righteous", steamAppId: 1184370, genre: "CRPG", playtime: 120, desc: "“史诗级的 CRPG。凡人飞升成神，对抗恶魔大军，宏大叙事。”" },
  { id: 77, name_zh: "《废土 3》", name_en: "Wasteland 3", steamAppId: 719040, genre: "CRPG/策略", playtime: 50, desc: "“末世科罗拉多的黑色幽默。策略战棋与 RPG 的完美结合。”" },
  { id: 78, name_zh: "《沙石镇时光》", name_en: "My Time at Sandrock", steamAppId: 1084600, genre: "模拟/RPG", playtime: 60, desc: "“国产模拟经营的佳作，在荒漠中通过工坊建设重现文明。”" },
  { id: 79, name_zh: "《深海迷航》", name_en: "Subnautica", steamAppId: 264710, genre: "生存/恐怖", playtime: 40, desc: "“深海恐惧与探索欲的拉锯战。也是最好的生存建造游戏之一。”" },
  { id: 80, name_zh: "《吸血鬼：避世血族》", name_en: "Vampire: The Masquerade - Bloodlines", steamAppId: 2600, genre: "RPG/经典", playtime: 30, desc: "“吸血鬼题材 RPG 的不朽经典。虽然 Bug 多，但剧本和氛围无可替代。”" },

  // === 81-100: 独立、恐怖与惊悚 ===
  { id: 81, name_zh: "《生化危机 4 重制版》", name_en: "Resident Evil 4 Remake", steamAppId: 2050650, genre: "恐怖/动作", playtime: 15, desc: "“动作生存恐怖的皇帝。完美的节奏把控，里昂最帅的时刻。”" },
  { id: 82, name_zh: "《寂静岭 2 重制版》", name_en: "Silent Hill 2", steamAppId: 2124490, genre: "恐怖/心理", playtime: 15, desc: "“心理恐怖的巅峰回归。大雾弥漫的小镇，关于罪恶与惩罚的自我审判。”" },
  { id: 83, name_zh: "《异形：隔离》", name_en: "Alien: Isolation", steamAppId: 214490, genre: "恐怖/潜行", playtime: 20, desc: "“最还原电影的异形游戏。异形 AI 极其聪明，压迫感让人无法呼吸。”" },
  { id: 84, name_zh: "《恶灵附身》", name_en: "The Evil Within", steamAppId: 268050, genre: "恐怖/生存", playtime: 15, desc: "“三上真司的回归。扭曲的现实，血腥的艺术，硬核的生存恐怖。”" },
  { id: 85, name_zh: "《Inside》", name_en: "Inside", steamAppId: 304430, genre: "解谜/恐怖", playtime: 4, desc: "“无言的黑暗童话。全程压抑，最后的结局让人震撼且不知所措。”" },
  { id: 86, name_zh: "《小小梦魇 2》", name_en: "Little Nightmares II", steamAppId: 860510, genre: "恐怖/解谜", playtime: 6, desc: "“精致的恐怖解谜。两个小人的牵手冒险，结局却无比致郁。”" },
  { id: 87, name_zh: "《森林之子》", name_en: "Sons of the Forest", steamAppId: 1326470, genre: "恐怖/生存", playtime: 25, desc: "“恐怖生存的进化。凯文是最好的伙伴，野人AI极具压迫感。”" },
  { id: 88, name_zh: "《Omori》", name_en: "Omori", steamAppId: 1150690, genre: "RPG/心理恐怖", playtime: 20, desc: "“可爱的画风下隐藏着极度致郁的心理恐怖。关于抑郁、自责与和解。”" },
  { id: 89, name_zh: "《信使》", name_en: "The Messenger", steamAppId: 764790, genre: "动作/平台", playtime: 12, desc: "“从 8 位机到 16 位机的穿越。复古忍龙风格，却有着惊人的 Meta 剧情反转。”" },
  { id: 90, name_zh: "《武士 零》", name_en: "Katana ZERO", steamAppId: 460950, genre: "动作/赛博朋克", playtime: 6, desc: "“赛博朋克武士。一击必杀的快感，配合迷幻的剧情和神级配乐。”" },
  { id: 91, name_zh: "《巴别塔圣歌》", name_en: "Chants of Sennaar", steamAppId: 1931770, genre: "解谜/语言", playtime: 10, desc: "“语言解谜的神作。通过破译古文字来沟通不同的种族，立意高远。”" },
  { id: 92, name_zh: "《Baba Is You》", name_en: "Baba Is You", steamAppId: 736260, genre: "解谜/逻辑", playtime: 15, desc: "“逻辑解谜的天花板。改变规则本身来通关，烧脑到怀疑人生。”" },
  { id: 93, name_zh: "《OneShot》", name_en: "OneShot", steamAppId: 420530, genre: "冒险/Meta", playtime: 8, desc: "“打破第四面墙的又一神作。你不是在玩游戏，你是在拯救这只猫（Niko）。”" },
  { id: 94, name_zh: "《史莱姆牧场》", name_en: "Slime Rancher", steamAppId: 433340, genre: "模拟/可爱", playtime: 20, desc: "“极致的可爱与解压。看着 Q 弹的史莱姆，心情都会变好。”" },
  { id: 95, name_zh: "《这是警察》", name_en: "This Is the Police", steamAppId: 443810, genre: "策略/模拟", playtime: 15, desc: "“黑白两道的艰难抉择。在退休前赚够养老金，充满黑色电影的质感。”" },
  { id: 96, name_zh: "《冰汽时代》", name_en: "Frostpunk", steamAppId: 323190, genre: "模拟/生存", playtime: 15, desc: "“社会生存模拟。在严寒末世中，‘这一切值得吗？’是对玩家灵魂的拷问。”" },
  { id: 97, name_zh: "《暗黑地牢 2》", name_en: "Darkest Dungeon II", steamAppId: 1940340, genre: "肉鸽/RPG", playtime: 40, desc: "“在绝望的马车旅途中寻找希望。美术风格进化，依然压力拉满。”" },
  { id: 98, name_zh: "《黑神话：悟空》", name_en: "Black Myth: Wukong", steamAppId: 2358720, genre: "ARPG/神话", playtime: 35, desc: "“国产 3A 的里程碑。美术表现力世界顶尖，重走西游路的文化震撼。”" },
  { id: 99, name_zh: "《吸血鬼幸存者》", name_en: "Vampire Survivors", steamAppId: 1794680, genre: "肉鸽/休闲", playtime: 20, desc: "“极其上瘾的割草体验。用最简单的操作带来最纯粹的多巴胺分泌。”" },
  { id: 100, name_zh: "《往日不再》", name_en: "Days Gone", steamAppId: 1259420, genre: "动作/生存", playtime: 40, desc: "“被低估的开放世界丧尸神作。骑着摩托车面对汹涌尸潮的压迫感。”" },

  // === 101-120: 叙事、解谜与艺术 (Part 2) ===
  { id: 101, name_zh: "《半衰期 2》", name_en: "Half-Life 2", steamAppId: 220, genre: "FPS/叙事", playtime: 15, desc: "“FPS 叙事的里程碑。重力枪的物理玩法至今不过时，17号城市的压抑感令人窒息。”" },
  { id: 102, name_zh: "《传送门》", name_en: "Portal", steamAppId: 400, genre: "解谜/神作", playtime: 4, desc: "“蛋糕是个谎言。短小精悍的完美解谜，GLaDOS 的初次登场令人难忘。”" },
  { id: 103, name_zh: "《生化奇兵》", name_en: "BioShock", steamAppId: 7670, genre: "FPS/惊悚", playtime: 12, desc: "“在极乐城的水下废墟中，‘Would you kindly’ 揭示了最震撼的剧情反转。”" },
  { id: 104, name_zh: "《肯塔基0号路》", name_en: "Kentucky Route Zero", steamAppId: 231200, genre: "叙事/魔幻现实", playtime: 8, desc: "“电子游戏界的《百年孤独》。充满诗意、戏剧感和哲学思考的公路之旅。”" },
  { id: 105, name_zh: "《整理房间》", name_en: "Unpacking", steamAppId: 1135690, genre: "休闲/叙事", playtime: 4, desc: "“通过整理物品来体验一段人生。无需文字，物品的变迁就是故事。”" },
  { id: 106, name_zh: "《见证者》", name_en: "The Witness", steamAppId: 210970, genre: "解谜/开放世界", playtime: 30, desc: "“一座充满谜题的孤岛。不仅仅是连线，更是对观察力和顿悟的终极考验。”" },
  { id: 107, name_zh: "《塔洛斯法则》", name_en: "The Talos Principle", steamAppId: 257510, genre: "解谜/哲学", playtime: 20, desc: "“在解谜中探讨人工智能、意识与人类的本质，硬科幻爱好者的福音。”" },
  { id: 108, name_zh: "《看火人》", name_en: "Firewatch", steamAppId: 383870, genre: "步行模拟/叙事", playtime: 5, desc: "“两个逃避现实的人，通过对讲机产生的情感羁绊，怀俄明州的夕阳绝美。”" },
  { id: 109, name_zh: "《林中之夜》", name_en: "Night in the Woods", steamAppId: 481510, genre: "叙事/冒险", playtime: 10, desc: "“关于返乡、成长与存在主义焦虑的动物寓言，剧本极其细腻。”" },
  { id: 110, name_zh: "《请出示证件》", name_en: "Papers, Please", steamAppId: 239030, genre: "模拟/反乌托邦", playtime: 6, desc: "“在极权国家的边境做检查员。每一个盖章都关乎他人的命运和家人的温饱。”" },
  { id: 111, name_zh: "《邪恶冥刻》", name_en: "Inscryption", steamAppId: 1092790, genre: "卡牌/Meta", playtime: 12, desc: "“伪装成卡牌游戏的心理恐怖与解谜神作，打破第四面墙的体验独一无二。”" },
  { id: 112, name_zh: "《她的故事》", name_en: "Her Story", steamAppId: 368370, genre: "FMV/推理", playtime: 3, desc: "“非线性叙事的先驱。通过检索关键词查看审讯录像，拼凑出破碎的真相。”" },
  { id: 113, name_zh: "《不朽》", name_en: "Immortality", steamAppId: 1350200, genre: "FMV/惊悚", playtime: 10, desc: "“三部未上映的电影，寻找失踪的女演员。通过点击画面中的物体跳转时空，细思极恐。”" },
  { id: 114, name_zh: "《迷失》", name_en: "Stray", steamAppId: 1332010, genre: "冒险/猫咪", playtime: 6, desc: "“在赛博朋克城市中做一只猫。按O喵喵叫，场景细节和氛围感无敌。”" },
  { id: 115, name_zh: "《灵魂旅人》", name_en: "Spiritfarer", steamAppId: 972660, genre: "模拟/情感", playtime: 30, desc: "“关于如何好好告别的游戏。作为灵魂摆渡人，照顾幽灵直到他们准备好离开。”" },
  { id: 116, name_zh: "《机械迷城》", name_en: "Machinarium", steamAppId: 40700, genre: "冒险/解谜", playtime: 6, desc: "“捷克工作室的手绘蒸汽朋克经典。没有对白，只有小机器人的纯真冒险。”" },
  { id: 117, name_zh: "《时空幻境》", name_en: "Braid", steamAppId: 26800, genre: "平台/解谜", playtime: 6, desc: "“独立游戏的里程碑。操控时间来解谜，结局对‘拯救公主’进行了深刻的解构。”" },
  { id: 118, name_zh: "《意航员 2》", name_en: "Psychonauts 2", steamAppId: 607080, genre: "平台/创意", playtime: 15, desc: "“进入精神世界的大冒险。关卡设计脑洞大开，美术风格独树一帜。”" },
  { id: 119, name_zh: "《遗忘之城》", name_en: "The Forgotten City", steamAppId: 874260, genre: "推理/时间循环", playtime: 10, desc: "“源自老滚5的MOD神作。在古罗马城市中探索‘黄金法则’，剧本逻辑严密。”" },
  { id: 120, name_zh: "《茧》", name_en: "Cocoon", steamAppId: 1497440, genre: "解谜/冒险", playtime: 6, desc: "“世界套娃，无需文字引导的顶级解谜设计。Inside设计师的又一神作。”" },

  // === 121-140: 经典与现代 RPG (Part 2) ===
  { id: 121, name_zh: "《上古卷轴 IV：湮没》", name_en: "The Elder Scrolls IV: Oblivion", steamAppId: 22330, genre: "RPG/开放世界", playtime: 100, desc: "“拥有系列最好的公会任务线（如黑暗兄弟会）。西罗帝尔的风景如油画般美丽。”" },
  { id: 122, name_zh: "《辐射 4》", name_en: "Fallout 4", steamAppId: 377160, genre: "RPG/废土", playtime: 80, desc: "“捡垃圾与建造的乐趣无穷。波士顿废土的探索循环让人停不下来。”" },
  { id: 123, name_zh: "《龙腾世纪：起源》", name_en: "Dragon Age: Origins", steamAppId: 17450, genre: "CRPG/史诗", playtime: 60, desc: "“BioWare 的奇幻巅峰。灰袍守护者的起源故事，队友刻画极其深刻。”" },
  { id: 124, name_zh: "《星球大战：旧共和国武士》", name_en: "Star Wars: KOTOR", steamAppId: 32370, genre: "CRPG/星战", playtime: 30, desc: "“最好的星战游戏剧本。剧情反转是游戏史上的经典时刻。”" },
  { id: 125, name_zh: "《如龙 7：光与暗的行踪》", name_en: "Yakuza: Like a Dragon", steamAppId: 1235140, genre: "JRPG/剧情", playtime: 50, desc: "“系列成功转型的回合制RPG。春日一番的热血中二与成年人的辛酸完美融合。”" },
  { id: 126, name_zh: "《女神异闻录 3 Reload》", name_en: "Persona 3 Reload", steamAppId: 2161700, genre: "JRPG/校园", playtime: 70, desc: "“人活着就是为了记住死亡。画面与系统全面现代化的经典重制。”" },
  { id: 127, name_zh: "《最终幻想 VI》", name_en: "Final Fantasy VI Pixel Remaster", steamAppId: 1173820, genre: "JRPG/像素", playtime: 40, desc: "“SFC时代的最高杰作。群像剧的巅峰，凯夫卡的笑声和歌剧院的演出。”" },
  { id: 128, name_zh: "《时空之轮》", name_en: "Chrono Trigger", steamAppId: 613830, genre: "JRPG/穿越", playtime: 25, desc: "“梦之队的遗产。穿越时空的宏大冒险，至今仍是JRPG的教科书。”" },
  { id: 129, name_zh: "《真·女神转生 V：复仇》", name_en: "Shin Megami Tensei V: Vengeance", steamAppId: 2634010, genre: "JRPG/硬核", playtime: 60, desc: "“回合制战斗系统的天花板。末世东京的氛围与仲魔合成的深度令人着迷。”" },
  { id: 130, name_zh: "《星之海洋 2 第二个故事 R》", name_en: "Star Ocean The Second Story R", steamAppId: 2238900, genre: "JRPG/重制", playtime: 40, desc: "“HD-2D与3D背景结合的完美重制。战斗爽快，道具制作系统深不见底。”" },
  { id: 131, name_zh: "《三角战略》", name_en: "Triangle Strategy", steamAppId: 1850510, genre: "SRPG/战棋", playtime: 40, desc: "“信念的天平决定国家命运。剧情严肃宏大，战棋玩法扎实。”" },
  { id: 132, name_zh: "《战场女武神》", name_en: "Valkyria Chronicles", steamAppId: 294860, genre: "SRPG/手绘", playtime: 30, desc: "“水彩手绘风格的战争剧。独特的BLiTZ战斗系统将策略与射击完美结合。”" },
  { id: 133, name_zh: "《永恒之柱 II：死之火焰》", name_en: "Pillars of Eternity II: Deadfire", steamAppId: 560130, genre: "CRPG/航海", playtime: 50, desc: "“黑曜石的文字功底。在群岛之间航行，探索神明与凡人的纠葛。”" },
  { id: 134, name_zh: "《废土 2：导演剪辑版》", name_en: "Wasteland 2: Director's Cut", steamAppId: 404730, genre: "CRPG/废土", playtime: 50, desc: "“辐射的精神前作回归。硬核的策略战斗与黑色幽默的废土世界。”" },
  { id: 135, name_zh: "《暴行》", name_en: "Tyranny", steamAppId: 362960, genre: "CRPG/反派", playtime: 25, desc: "“扮演邪恶霸主的执行官。体验邪恶获胜后的世界，法术组合系统非常有创意。”" },
  { id: 136, name_zh: "《火炬之光 2》", name_en: "Torchlight II", steamAppId: 200710, genre: "ARPG/刷宝", playtime: 20, desc: "“暗黑风格的刷宝佳作，画风明亮，职业搭配自由度高。”" },
  { id: 137, name_zh: "《无主之地 2》", name_en: "Borderlands 2", steamAppId: 49520, genre: "FPS/刷宝", playtime: 40, desc: "“帅杰克是游戏史上最迷人的反派之一。刷宝射击的巅峰体验。”" },
  { id: 138, name_zh: "《杀出重围：人类分裂》", name_en: "Deus Ex: Mankind Divided", steamAppId: 337000, genre: "沉浸模拟/赛博", playtime: 25, desc: "“布拉格的箱庭设计极其精妙。虽然剧情有遗憾，但玩法自由度极高。”" },
  { id: 139, name_zh: "《羞辱》", name_en: "Dishonored", steamAppId: 205100, genre: "沉浸模拟/潜行", playtime: 15, desc: "“复仇的刺客。油画般的鲸油朋克世界，瞬移暗杀的快感无与伦比。”" },
  { id: 140, name_zh: "《潜行者：切尔诺贝利的阴影》", name_en: "S.T.A.L.K.E.R.: Shadow of Chernobyl", steamAppId: 4500, genre: "FPS/生存", playtime: 20, desc: "“切尔诺贝利的恐怖氛围。硬核的生存机制与充满未知变异的禁区。”" },

  // === 141-160: 动作、硬核与开放世界 (Part 2) ===
  { id: 141, name_zh: "《黑暗之魂 重制版》", name_en: "Dark Souls: Remastered", steamAppId: 570940, genre: "ARPG/魂系", playtime: 50, desc: "“传火的开始。罗德兰的立体地图设计至今仍是业界教科书。”" },
  { id: 142, name_zh: "《仁王 2》", name_en: "Nioh 2", steamAppId: 1325200, genre: "ARPG/动作", playtime: 60, desc: "“战斗系统的深度令人发指。残心、妖怪技与三种架势的完美融合。”" },
  { id: 143, name_zh: "《匹诺曹的谎言》", name_en: "Lies of P", steamAppId: 1627720, genre: "ARPG/魂系", playtime: 30, desc: "“最优秀的非FS社魂系游戏。暗黑童话风格，武器组装系统很有新意。”" },
  { id: 144, name_zh: "《龙之信条：黑暗觉者》", name_en: "Dragon's Dogma: Dark Arisen", steamAppId: 367500, genre: "ARPG/开放世界", playtime: 40, desc: "“攀爬巨兽的战斗体验独一无二。随从系统让单人冒险不再孤单。”" },
  { id: 145, name_zh: "《装甲核心 VI》", name_en: "Armored Core VI", steamAppId: 1888160, genre: "动作/机甲", playtime: 20, desc: "“男人的浪漫就是开机甲。FS社硬核机战的回归，组装与战斗都极具深度。”" },
  { id: 146, name_zh: "《鬼泣 5》", name_en: "Devil May Cry 5", steamAppId: 601150, genre: "动作/砍杀", playtime: 15, desc: "“动作天尊的回归。三个角色三种完全不同的极致战斗体验，SSS评价的爽快。”" },
  { id: 147, name_zh: "《蝙蝠侠：阿卡姆之城》", name_en: "Batman: Arkham City", steamAppId: 200260, genre: "动作/超英", playtime: 20, desc: "“超级英雄改篇游戏的巅峰。完美的战斗节奏，哥谭市的黑暗魅力。”" },
  { id: 148, name_zh: "《漫威蜘蛛侠：重制版》", name_en: "Marvel's Spider-Man Remastered", steamAppId: 1817070, genre: "动作/开放世界", playtime: 25, desc: "“在纽约高楼间摆荡的快感无可替代。剧情对彼得·帕克的刻画非常深入。”" },
  { id: 149, name_zh: "《战神 (2018)》", name_en: "God of War", steamAppId: 1593500, genre: "动作/冒险", playtime: 25, desc: "“一镜到底的视听奇迹。从复仇战神到老父亲的转变，战斗手感扎实厚重。”" },
  { id: 150, name_zh: "《地平线：零之曙光》", name_en: "Horizon Zero Dawn", steamAppId: 1151640, genre: "ARPG/开放世界", playtime: 40, desc: "“机械恐龙与原始部落的奇妙结合。揭开世界毁灭真相的过程令人着迷。”" },
  { id: 151, name_zh: "《合金装备 V：幻痛》", name_en: "Metal Gear Solid V: The Phantom Pain", steamAppId: 287700, genre: "潜行/沙盒", playtime: 60, desc: "“潜行玩法的极致自由度。虽然剧情有遗憾，但游戏性是满分。”" },
  { id: 152, name_zh: "《杀手 3》", name_en: "Hitman World of Assassination", steamAppId: 1659040, genre: "潜行/沙盒", playtime: 50, desc: "“杀手三部曲的集大成者。关卡设计精妙绝伦，一百种暗杀方式等你发现。”" },
  { id: 153, name_zh: "《细胞分裂：混沌理论》", name_en: "Tom Clancy's Splinter Cell: Chaos Theory", steamAppId: 13570, genre: "潜行/经典", playtime: 12, desc: "“硬核潜行的巅峰。光影与声音的博弈，山姆·费雪最帅的时刻。”" },
  { id: 154, name_zh: "《地铁：离去》", name_en: "Metro Exodus", steamAppId: 412020, genre: "FPS/生存", playtime: 20, desc: "“走出地铁，踏上火车之旅。半开放世界的废土风景绝美且残酷。”" },
  { id: 155, name_zh: "《孤岛惊魂 3》", name_en: "Far Cry 3", steamAppId: 220240, genre: "FPS/开放世界", playtime: 20, desc: "“瓦阿斯的疯狂定义了整个系列。美丽的热带海岛与疯狂的海盗。”" },
  { id: 156, name_zh: "《德军总部：新秩序》", name_en: "Wolfenstein: The New Order", steamAppId: 201810, genre: "FPS/剧情", playtime: 12, desc: "“如果纳粹赢了二战？B.J.布拉柯威兹教他们做人。剧情与射击手感俱佳。”" },
  { id: 157, name_zh: "《毁灭战士 (2016)》", name_en: "DOOM", steamAppId: 379720, genre: "FPS/爽游", playtime: 12, desc: "“撕裂与重金属。FPS 鼻祖的完美重启，纯粹的杀戮快感。”" },
  { id: 158, name_zh: "《究极杀戮》", name_en: "Ultrakill", steamAppId: 1229490, genre: "FPS/复古", playtime: 15, desc: "“机械就是燃料，地狱已经满了。把 FPS 玩成鬼泣的超高速爽游。”" },
  { id: 159, name_zh: "《迈阿密热线》", name_en: "Hotline Miami", steamAppId: 219150, genre: "动作/俯视", playtime: 5, desc: "“迷幻的电子乐，暴力的像素画。一击必杀的快节奏试错体验。”" },
  { id: 160, name_zh: "《死亡空间 2》", name_en: "Dead Space 2", steamAppId: 47780, genre: "恐怖/动作", playtime: 10, desc: "“艾萨克有了语音，动作性增强。经典的肢解恐怖与幻觉叙事。”" },

  // === 161-180: 策略、模拟与生存 (Part 2) ===
  { id: 161, name_zh: "《群星》", name_en: "Stellaris", steamAppId: 281990, genre: "4X/科幻", playtime: 100, desc: "“银河级的宏大战略。从探索星系到建立联邦，或者成为银河危机。”" },
  { id: 162, name_zh: "《十字军之王 3》", name_en: "Crusader Kings III", steamAppId: 1158310, genre: "大战略/RPG", playtime: 100, desc: "“中世纪宫廷模拟器。家族繁衍、阴谋诡计与宗教战争。”" },
  { id: 163, name_zh: "《帝国时代 II：决定版》", name_en: "Age of Empires II: Definitive Edition", steamAppId: 813780, genre: "RTS/经典", playtime: 50, desc: "“RTS 的常青树。重制版诚意满满，战役模式就是一部活的历史书。”" },
  { id: 164, name_zh: "《全面战争：幕府将军 2》", name_en: "Total War: SHOGUN 2", steamAppId: 34330, genre: "RTS/战术", playtime: 60, desc: "“全战系列美术与氛围的巅峰。日本战国时代的铁炮与武士。”" },
  { id: 165, name_zh: "《影子战术：将军之刃》", name_en: "Shadow Tactics: Blades of the Shogun", steamAppId: 418240, genre: "RTT/潜行", playtime: 25, desc: "“盟军敢死队玩法的完美复兴。江户时代的忍者小队配合天衣无缝。”" },
  { id: 166, name_zh: "《幽浮：未知敌人》", name_en: "XCOM: Enemy Unknown", steamAppId: 200510, genre: "战棋/策略", playtime: 30, desc: "“现代 XCOM 的重启之作。虽然没有二代完善，但氛围更具压迫感。”" },
  { id: 167, name_zh: "《城市：天际线》", name_en: "Cities: Skylines", steamAppId: 255710, genre: "模拟/建造", playtime: 50, desc: "“最好的现代城市建造游戏。解决交通拥堵才是游戏的核心。”" },
  { id: 168, name_zh: "《缺氧》", name_en: "Oxygen Not Included", steamAppId: 457140, genre: "模拟/生存", playtime: 60, desc: "“硬核的物理气体模拟。看着小人在太空殖民地为了生存手忙脚乱。”" },
  { id: 169, name_zh: "《戴森球计划》", name_en: "Dyson Sphere Program", steamAppId: 1366540, genre: "模拟/自动化", playtime: 80, desc: "“国产科幻之光。从手搓零件到包裹恒星的戴森球，宇宙级的工业浪漫。”" },
  { id: 170, name_zh: "《幸福工厂》", name_en: "Satisfactory", steamAppId: 526870, genre: "模拟/FPS", playtime: 80, desc: "“3D 版的异星工厂。第一人称视角下的巨型工厂建设，垂直输送带极其治愈。”" },
  { id: 171, name_zh: "《漫漫长夜》", name_en: "The Long Dark", steamAppId: 305620, genre: "生存", playtime: 30, desc: "“孤独的雪地生存体验。没有丧尸，只有寒冷、饥饿和野生动物。”" },
  { id: 172, name_zh: "《无人深空》", name_en: "No Man's Sky", steamAppId: 275850, genre: "生存/太空", playtime: 80, desc: "“游戏史上最伟大的救赎。从发售时的空洞到如今的无限宇宙。”" },
  { id: 173, name_zh: "《潜水员戴夫》", name_en: "Dave the Diver", steamAppId: 1868140, genre: "冒险/模拟", playtime: 25, desc: "“白天捕鱼，晚上开店。玩法缝合得恰到好处，充满惊喜的海洋蓝洞。”" },
  { id: 174, name_zh: "《渔帆暗涌》", name_en: "Dredge", steamAppId: 1562430, genre: "冒险/克苏鲁", playtime: 12, desc: "“在克苏鲁海域钓鱼。管理库存，升级船只，不要在夜晚驶入迷雾。”" },
  { id: 175, name_zh: "《以撒的结合：重生》", name_en: "The Binding of Isaac: Rebirth", steamAppId: 250900, genre: "肉鸽/射击", playtime: 100, desc: "“肉鸽游戏的常青树。道具组合近乎无限，黑色幽默与宗教隐喻。”" },
  { id: 176, name_zh: "《挺进地牢》", name_en: "Enter the Gungeon", steamAppId: 311690, genre: "肉鸽/弹幕", playtime: 40, desc: "“为了过去而战。充满枪械梗的弹幕地狱，翻滚躲避是核心。”" },
  { id: 177, name_zh: "《洞穴探险 2》", name_en: "Spelunky 2", steamAppId: 418530, genre: "肉鸽/平台", playtime: 50, desc: "“高难度平台肉鸽的教科书。每一次死亡都是一堂物理课。”" },
  { id: 178, name_zh: "《Noita》", name_en: "Noita", steamAppId: 881100, genre: "肉鸽/物理", playtime: 30, desc: "“每一个像素都有物理模拟。魔法合成系统极其复杂，花式自杀模拟器。”" },
  { id: 179, name_zh: "《小丑牌》", name_en: "Balatro", steamAppId: 2379780, genre: "肉鸽/卡牌", playtime: 40, desc: "“电子毒品。把德州扑克玩出了肉鸽的新高度，数值膨胀的快感。”" },
  { id: 180, name_zh: "《欧洲卡车模拟 2》", name_en: "Euro Truck Simulator 2", steamAppId: 227300, genre: "模拟/驾驶", playtime: 100, desc: "“治疗路怒症的神器。听着电台在欧洲的高速公路上运货，极致的放松。”" },

  // === 181-200: 恐怖、动作与精选补充 ===
  { id: 181, name_zh: "《生化危机 1 重制版》", name_en: "Resident Evil HD Remaster", steamAppId: 304240, genre: "恐怖/生存", playtime: 12, desc: "“生存恐怖的教科书。洋馆的箱庭设计完美无缺，资源管理的压力。”" },
  { id: 182, name_zh: "《生化危机 7》", name_en: "Resident Evil 7", steamAppId: 418370, genre: "恐怖/第一人称", playtime: 10, desc: "“回归恐怖本源。贝克一家的晚宴是系列最恐怖的开场之一。”" },
  { id: 183, name_zh: "《死亡空间 重制版》", name_en: "Dead Space", steamAppId: 1693980, genre: "恐怖/科幻", playtime: 12, desc: "“肢解战斗的压迫感。石村号的音效设计让人全程紧绷。”" },
  { id: 184, name_zh: "《失忆症：地堡》", name_en: "Amnesia: The Bunker", steamAppId: 1944430, genre: "恐怖/沉浸", playtime: 6, desc: "“半开放式地图，怪物AI随机。在一战地堡中体验真正的绝望与无助。”" },
  { id: 185, name_zh: "《信号》", name_en: "SIGNALIS", steamAppId: 1262350, genre: "恐怖/复古", playtime: 8, desc: "“致敬经典生存恐怖。复古的画风，隐晦的剧情，关于承诺与记忆。”" },
  { id: 186, name_zh: "《恶灵附身 2》", name_en: "The Evil Within 2", steamAppId: 601430, genre: "恐怖/半开放", playtime: 15, desc: "“比一代更成熟的玩法。半开放世界的探索与父爱的救赎故事。”" },
  { id: 187, name_zh: "《瘟疫传说：无罪》", name_en: "A Plague Tale: Innocence", steamAppId: 752590, genre: "动作/潜行", playtime: 12, desc: "“中世纪的鼠疫噩梦。姐弟俩在战火与鼠潮中的求生之旅，情感真挚。”" },
  { id: 188, name_zh: "《瘟疫传说：安魂曲》", name_en: "A Plague Tale: Requiem", steamAppId: 1182900, genre: "动作/潜行", playtime: 18, desc: "“画质与玩法的全面进化。更加宏大的场景，更加令人心碎的结局。”" },
  { id: 189, name_zh: "《瑞奇与叮当：时空跳转》", name_en: "Ratchet & Clank: Rift Apart", steamAppId: 1895880, genre: "动作/平台", playtime: 15, desc: "“像是在玩一部皮克斯动画电影。无缝的时空穿梭展示了SSD的威力。”" },
  { id: 190, name_zh: "《如龙：极 2》", name_en: "Yakuza Kiwami 2", steamAppId: 927380, genre: "动作冒险", playtime: 25, desc: "“双龙对决。关西之龙乡田龙司是系列最霸气的反派之一。”" },
  { id: 191, name_zh: "《审判之眼：死神的遗言》", name_en: "Judgment", steamAppId: 2058180, genre: "动作/悬疑", playtime: 30, desc: "“木村拓哉主演的侦探剧。剧本极其扎实，战斗比本传更爽快。”" },
  { id: 192, name_zh: "《审判之逝：湮灭的记忆》", name_en: "Lost Judgment", steamAppId: 2058190, genre: "动作/悬疑", playtime: 35, desc: "“探讨校园霸凌的深刻主题。战斗系统全面进化，如龙工作室的巅峰动作体验。”" },
  { id: 193, name_zh: "《小小梦魇》", name_en: "Little Nightmares", steamAppId: 424840, genre: "恐怖/解谜", playtime: 4, desc: "“穿着黄雨衣的小女孩，逃离巨大的贪颚号。压抑而精致的黑暗童话。”" },
  { id: 194, name_zh: "《九日》", name_en: "Nine Sols", steamAppId: 1809540, genre: "银河城/动作", playtime: 20, desc: "“道教朋克风格的‘2D 只狼’。格挡机制手感极佳，剧情深刻感人。”" },
  { id: 195, name_zh: "《桑塔》", name_en: "Sanabi", steamAppId: 1562700, genre: "平台/动作", playtime: 10, desc: "“赛博朋克铁钩动作。快节奏的移动，结局的剧情反转催泪核弹。”" },
  { id: 196, name_zh: "《暗影火炬城》", name_en: "F.I.S.T.: Forged In Shadow Torch", steamAppId: 1330470, genre: "银河城/动作", playtime: 15, desc: "“柴油朋克美学。挥舞巨大铁拳的兔子，国产银河恶魔城的佳作。”" },
  { id: 197, name_zh: "《终焉的莉莉》", name_en: "Ender Lilies: Quietus of the Knights", steamAppId: 1369630, genre: "银河城/RPG", playtime: 20, desc: "“唯美与凄凉并存。替身使者般的战斗方式，音乐好听到让人想哭。”" },
  { id: 198, name_zh: "《极限竞速：地平线 5》", name_en: "Forza Horizon 5", steamAppId: 1551360, genre: "赛车/开放世界", playtime: 60, desc: "“赛车游戏的画面标杆。在墨西哥的开放世界中自由驰骋，快乐至上。”" },
  { id: 199, name_zh: "《尘埃拉力赛 2.0》", name_en: "DiRT Rally 2.0", steamAppId: 690790, genre: "赛车/模拟", playtime: 50, desc: "“最硬核的拉力体验。路书就是圣经，每一个弯道都在挑战极限。”" },
  { id: 200, name_zh: "《光环：士官长合集》", name_en: "Halo: The Master Chief Collection", steamAppId: 976730, genre: "FPS/经典", playtime: 40, desc: "“FPS 的传奇合集。士官长的史诗旅程，重温科幻射击的黄金时代。”" }
];